apiVersion: apps/v1
kind: Deployment
metadata:
  name: osc
  namespace: osc
  labels:
    app: osc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osc
  template:
    metadata:
      labels:
        app: osc
    spec:
      containers:
        - name: osc
          image: osc:1.0.0-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: huaweicloud
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /osc/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /osc/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10