# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
---
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG

xpanse:
  ai:
    llm:
      providerApiEndpointUrl: http://localhost:11434
      modelName: meta-llama/llama-4-scout-17b-16e-instruct
      providerApiKey: ""
    docker:
      registry-url: "ghcr.io"
      registry-username: ""
      registry-password: ""
      registry-organization: ""
      proxy-url: ""
