# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.
---
otel:
  exporter:
    otlp:
      endpoint: http://localhost:4318
    health-check-port: 13133
  sdk:
    disabled: false